sector_tuner:
  ros__parameters:
    global_limit: 1.0
    n_sectors: 5
    Sector0:
      start: 0
      end: 44
      scaling: 0.5
      t_clip_min: 1.1
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 45
      end: 86
      scaling: 0.5
      t_clip_min: 1.1
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 87
      end: 154
      scaling: 0.5
      t_clip_min: 1.1
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 155
      end: 195
      scaling: 0.5
      t_clip_min: 1.1
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 196
      end: 224
      scaling: 0.5
      t_clip_min: 1.1
      only_FTG: false
      no_FTG: false
